const state={summary:null,anomalies:[],intelligence:[],metrics:null,forecast:null,verification:null,charts:{}};
const $=id=>document.getElementById(id); const fmt=n=>Number(n||0).toLocaleString('en-IN'); const pct=n=>`${(Number(n||0)*100).toFixed(1)}%`;
async function getJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path);return r.json()}
async function load(){
 try{
  const [summary,anomalies,intelligence,metrics,forecast,verification]=await Promise.all([
   getJSON('../data/phase4c/anomaly_summary.json'),getJSON('../data/phase4c/anomalies.json'),getJSON('../data/phase4/weather_intelligence.json'),getJSON('../data/phase4b/metrics.json'),getJSON('../data/phase4b/forecast_results.json'),getJSON('../data/phase3c/verification_summary.json')]);
  Object.assign(state,{summary,anomalies,intelligence,metrics,forecast,verification}); render(); toast('Live repository data loaded');
 }catch(e){console.error(e); toast('Open dashboard through a local server to load data');}
}
function render(){
 const s=state.summary,v=state.verification,m=state.metrics;
 $('observations').textContent=fmt(s.total_observations_analyzed);$('anomalies').textContent=fmt(s.total_anomalies);$('critical').textContent=fmt(s.anomalies_by_severity.CRITICAL);$('high').textContent=fmt(s.anomalies_by_severity.HIGH);$('anomalyRate').textContent=pct(s.anomaly_rate);$('evidenceScore').textContent=pct(v.average_evidence_support_score);$('sourceCount').textContent=fmt(Object.keys(s.anomalies_by_source||{}).length);$('navAnomalyCount').textContent=fmt(s.total_anomalies);
 $('severityTotal').textContent=fmt(s.total_anomalies); renderSeverity(s); renderMonthly(s); renderSources(s); renderVariables(s); renderModels(m); renderLatest(); renderForecast(); renderAnomalyExplorer(); renderIntelligence(); renderVerification(v); lucide.createIcons();
}
function renderMonthly(s){const labels=Object.keys(s.anomalies_by_month); const data=Object.values(s.anomalies_by_month); chart('monthlyChart','line',{labels,datasets:[{label:'Anomalies',data,borderColor:'#42a5ff',backgroundColor:'rgba(66,165,255,.10)',borderWidth:2,tension:.35,pointRadius:2,fill:true}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:8,font:{size:9}}},y:{grid:{color:'#eef0f4'},ticks:{font:{size:9}}}}});}
function renderSeverity(s){const entries=Object.entries(s.anomalies_by_severity); chart('severityChart','doughnut',{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),backgroundColor:entries.map(x=>severityColor(x[0])),borderWidth:0,hoverOffset:4}]},{cutout:'72%',plugins:{legend:{display:false}}});$('severityLegend').innerHTML=entries.map(([k,val])=>`<div class="legend-row"><span class="legend-dot" style="background:${severityColor(k)}"></span><span>${k}</span><b>${fmt(val)}</b></div>`).join('');}
function severityColor(k){return {CRITICAL:'#e5484d',HIGH:'#f59e0b',MEDIUM:'#d6bf35',LOW:'#2ba67b'}[k]||'#777'}
function renderSources(s){const max=Math.max(...Object.values(s.anomalies_by_source));$('sourceBars').innerHTML=Object.entries(s.anomalies_by_source).map(([k,v])=>`<div><div class="bar-label"><span>${k}</span><b>${fmt(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}
function renderVariables(s){const max=Math.max(...Object.values(s.anomalies_by_variable));$('variableList').innerHTML=Object.entries(s.anomalies_by_variable).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="mini-row"><span>${k.replace('_',' ')}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')}
function renderModels(m){$('modelCount').textContent=fmt(m.n_models_saved);const t=m.phase4b_1h_temperature_histgb;$('bestR2').textContent=Number(t.R2).toFixed(3);$('rainAuc').textContent='0.974';$('modelSnapshot').innerHTML=`<div class="model-box"><b>HistGradientBoosting</b><span>Temperature • 1h horizon</span><strong>${Number(t.R2).toFixed(3)} R²</strong><span>MAE ${Number(t.MAE).toFixed(3)} • RMSE ${Number(t.RMSE).toFixed(3)}</span></div>`}
function badge(x){return `<span class="badge badge-${String(x).toLowerCase()}">${x}</span>`}
function renderLatest(){const rows=[...state.anomalies].sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).slice(0,9);$('latestTable').innerHTML=rows.map(a=>`<tr><td>${new Date(a.timestamp).toLocaleString()}</td><td>${a.variable}</td><td>${a.source}</td><td>${Number(a.observed_value).toFixed(2)}</td><td>${Number(a.baseline_value).toFixed(2)}</td><td>${Number(a.anomaly_score).toFixed(2)}</td><td>${badge(a.severity)}</td></tr>`).join('')}
function renderForecast(){const f=state.forecast, rows=[];for(const variable of Object.keys(f)){for(const h of Object.keys(f[variable])){const x=f[variable][h];rows.push(`<tr><td>${variable}</td><td>${h}h</td><td>${x.best_model}</td><td>${x.MAE==null?'—':Number(x.MAE).toFixed(3)}</td><td>${x.RMSE==null?'—':Number(x.RMSE).toFixed(3)}</td><td>${x.R2==null?'ROC '+Number(x.ROC_AUC).toFixed(3):'R² '+Number(x.R2).toFixed(3)}</td></tr>`)} }$('forecastTable').innerHTML=rows.join('');const h=Object.keys(f.temperature);chart('forecastChart','line',{labels:h.map(x=>x+'h'),datasets:[{label:'Temperature R²',data:h.map(x=>f.temperature[x].R2),borderColor:'#42a5ff',backgroundColor:'rgba(66,165,255,.08)',borderWidth:2,tension:.3},{label:'Rainfall ROC-AUC',data:h.map(x=>f.rainfall[x].ROC_AUC),borderColor:'#35d39a',backgroundColor:'rgba(53,211,154,.08)',borderWidth:2,tension:.3}]},{scales:{y:{min:.4,max:1,grid:{color:'#eef0f4'}}}})}
function renderAnomalyExplorer(){const vars=[...new Set(state.anomalies.map(a=>a.variable))];$('anomalyFilter').innerHTML='<option value="all">All variables</option>'+vars.map(v=>`<option>${v}</option>`).join('');updateAnomalyTable();$('anomalyFilter').onchange=updateAnomalyTable;$('severityFilter').onchange=updateAnomalyTable}
function updateAnomalyTable(){const vf=$('anomalyFilter').value,sf=$('severityFilter').value;const rows=state.anomalies.filter(a=>(vf==='all'||a.variable===vf)&&(sf==='all'||a.severity===sf)).slice(0,500);$('anomalyCountText').textContent=`Showing ${fmt(rows.length)} records${rows.length<state.anomalies.length?' • filtered':' '}`;$('anomalyTable').innerHTML=rows.map(a=>`<tr><td>${new Date(a.timestamp).toLocaleString()}</td><td>${a.location||'India'}</td><td>${a.variable}</td><td>${Number(a.observed_value).toFixed(2)}</td><td>${Number(a.baseline_value).toFixed(2)}</td><td>${Number(a.anomaly_score).toFixed(2)}</td><td>${badge(a.severity)}</td><td>${a.method}</td></tr>`).join('')}
function renderIntelligence(){const arr=state.intelligence;const conf=arr.filter(x=>typeof x.overall_confidence==='number');const avg=conf.length?conf.reduce((a,x)=>a+x.overall_confidence,0)/conf.length:0;const matched=arr.filter(x=>x.source_agreement_match_status==='MATCHED').length;const supported=arr.filter(x=>x.corroboration_status==='SUPPORTED').length;$('intelligenceStats').innerHTML=[['Records',arr.length],['Matched sources',matched],['Supported reports',supported],['Avg confidence',pct(avg)]].map(x=>`<div class="insight"><span>${x[0]}</span><b>${typeof x[1]==='number'?fmt(x[1]):x[1]}</b></div>`).join('');$('confidenceRing').style.background=`conic-gradient(#6869eb 0 ${avg*100}%,#eef0f6 ${avg*100}% 100%)`;$('confidenceRing').querySelector('span').textContent=pct(avg);$('signalList').innerHTML=arr.slice(0,6).map(x=>`<div class="signal"><b>${x.corroboration_status||'No corroboration status'}</b><p>${new Date(x.timestamp).toLocaleString()} • ${x.source_agreement_match_status||'N/A'} • confidence ${x.overall_confidence==null?'—':pct(x.overall_confidence)}</p></div>`).join('')}
function renderVerification(v){$('totalReports').textContent=fmt(v.total_reports);$('supportedReports').textContent=fmt(v.verification_status_counts.SUPPORTED||0);$('insufficientReports').textContent=fmt(v.verification_status_counts.INSUFFICIENT_EVIDENCE||0);$('avgSupport').textContent=pct(v.average_evidence_support_score);const max=Math.max(...Object.values(v.verification_status_counts));$('verificationBars').innerHTML=Object.entries(v.verification_status_counts).map(([k,val])=>`<div><div class="bar-label"><span>${k.replaceAll('_',' ')}</span><b>${val}</b></div><div class="bar"><i style="width:${val/max*100}%"></i></div></div>`).join('')}
function chart(id,type,data,options){if(state.charts[id])state.charts[id].destroy();const el=$(id);if(!el)return;const base={responsive:true,maintainAspectRatio:false,color:'#8ea0b7',borderColor:'#22344b',...options,plugins:{...(options?.plugins||{}),legend:{...(options?.plugins?.legend||{}),labels:{color:'#9aa9bc',font:{size:9},boxWidth:9}}},scales:{x:{...(options?.scales?.x||{}),ticks:{color:'#71839a',...(options?.scales?.x?.ticks||{})},grid:{color:'#17283b',...(options?.scales?.x?.grid||{})}},y:{...(options?.scales?.y||{}),ticks:{color:'#71839a',...(options?.scales?.y?.ticks||{})},grid:{color:'#17283b',...(options?.scales?.y?.grid||{})}}}};state.charts[id]=new Chart(el,{type,data,options:base})}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));const titles={overview:'Weather Command Center',analytics:'Weather Analytics',anomalies:'Anomaly Explorer',intelligence:'Weather Intelligence',fusion:'Data Fusion',evidence:'Corroboration & Evidence',map:'Spatial Overview',reports:'Reports & Artifacts'};$('pageTitle').textContent=titles[page]||'Weather Intelligence';window.scrollTo({top:0,behavior:'smooth'});if(window.innerWidth<760)$('sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const n=e.target.closest('[data-page],[data-page-jump]');if(n){showPage(n.dataset.page||n.dataset.pageJump)}});$('refreshBtn').onclick=load;$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');function toast(msg){const t=$('toast');t.querySelector('span').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
lucide.createIcons();load();
